# https://github.com/Kaggle/docker-python/releases
FROM gcr.io/kaggle-gpu-images/python:v163

WORKDIR /workspace

# その他のライブラリ
RUN uv pip install --system \
    ruff \
    hydra-core \
    python-dotenv \
    rootutils \
    fire \
    japanize-matplotlib

# Claude Code
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g @anthropic-ai/claude-code
